#!/usr/bin/env bash
# setup-cmux.sh — provision the team-orchestra inside the current cmux workspace.
#
# Layout (from the CTO pane's point of view):
#   ┌────────────────────┬────────────────────┐
#   │  CTO (this pane)   │  DEV               │
#   ├────────────────────┼────────────────────┤
#   │  QA-CLAUDE         │  QA-GEMINI         │
#   ├────────────────────┴────────────────────┤
#   │  RECONCILER (full-width strip)          │
#   └─────────────────────────────────────────┘
#
# Run this from a cmux terminal (CMUX_WORKSPACE_ID will be set automatically).
# The pane you run it from becomes the CTO pane.

set -euo pipefail
ORCHESTRA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export ORCHESTRA_ROOT

# ─── Sanity checks ──────────────────────────────────────────────────────────
command -v cmux   >/dev/null || { echo "cmux CLI not found"   >&2; exit 1; }
command -v claude >/dev/null || { echo "claude CLI not found" >&2; exit 1; }
command -v gemini >/dev/null || { echo "gemini CLI not found" >&2; exit 1; }
cmux ping >/dev/null 2>&1   || { echo "cmux app is not running" >&2; exit 1; }

WORKSPACE="${CMUX_WORKSPACE_ID:-$(cmux current-workspace 2>/dev/null | tr -d ' ')}"
if [[ -z "$WORKSPACE" ]]; then
  echo "Could not detect a cmux workspace. Run this script from inside a cmux terminal." >&2
  exit 1
fi
echo "✓ workspace: $WORKSPACE"

# Make scripts executable.
chmod +x "$ORCHESTRA_ROOT"/bin/* "$ORCHESTRA_ROOT"/roles/*.sh "$ORCHESTRA_ROOT"/lib/reconciler.sh

# ─── Helpers ───────────────────────────────────────────────────────────────
list_surfaces() {
  # Print one surface ref per line (e.g. "surface:19").
  cmux list-panels --workspace "$WORKSPACE" 2>/dev/null \
    | grep -oE 'surface:[0-9]+' | sort -u
}

focused_surface() {
  cmux list-panels --workspace "$WORKSPACE" 2>/dev/null \
    | awk '/\[focused\]/ {for (i=1;i<=NF;i++) if ($i ~ /^surface:[0-9]+$/) {print $i; exit}}'
}

# split <from_surface> <left|right|up|down> → echoes the new surface ref.
split_from() {
  local from="$1" dir="$2"
  cmux focus-panel --panel "$from" --workspace "$WORKSPACE" >/dev/null
  local before; before="$(list_surfaces)"
  cmux new-pane --direction "$dir" --workspace "$WORKSPACE" --focus false >/dev/null
  # Give cmux a beat to register the new surface.
  local tries=0 after new
  while (( tries < 30 )); do
    after="$(list_surfaces)"
    new="$(comm -13 <(echo "$before") <(echo "$after"))"
    if [[ -n "$new" ]]; then
      echo "$(echo "$new" | head -n1)"
      return 0
    fi
    sleep 0.1
    ((tries++))
  done
  echo "✗ failed to detect new surface after split from $from $dir" >&2
  return 1
}

# send_cmd <surface> <command-string>
send_cmd() {
  local surface="$1" cmd="$2"
  # \n at the end submits.
  cmux send-panel --panel "$surface" --workspace "$WORKSPACE" -- "$cmd"$'\n'
}

# ─── Identify CTO pane ─────────────────────────────────────────────────────
CTO_SURFACE="$(focused_surface)"
if [[ -z "$CTO_SURFACE" ]]; then
  echo "Could not detect focused surface. Aborting." >&2
  exit 1
fi
echo "✓ CTO pane: $CTO_SURFACE"

# ─── Build the layout ──────────────────────────────────────────────────────
echo "→ creating DEV pane (split right of CTO)…"
DEV_SURFACE="$(split_from "$CTO_SURFACE" right)"
echo "  DEV       = $DEV_SURFACE"

echo "→ creating QA-CLAUDE pane (split below CTO)…"
QA_CLAUDE_SURFACE="$(split_from "$CTO_SURFACE" down)"
echo "  QA-CLAUDE = $QA_CLAUDE_SURFACE"

echo "→ creating QA-GEMINI pane (split below DEV)…"
QA_GEMINI_SURFACE="$(split_from "$DEV_SURFACE" down)"
echo "  QA-GEMINI = $QA_GEMINI_SURFACE"

echo "→ creating RECONCILER pane (split below QA-GEMINI)…"
RECON_SURFACE="$(split_from "$QA_GEMINI_SURFACE" down)"
echo "  RECON     = $RECON_SURFACE"

# Persist refs for the teardown script and CTO helpers.
mkdir -p "$ORCHESTRA_ROOT/.runtime"
cat > "$ORCHESTRA_ROOT/.runtime/cmux.env" <<EOF
# Generated by setup-cmux.sh on $(date '+%Y-%m-%d %H:%M:%S')
CMUX_WORKSPACE='$WORKSPACE'
CTO_SURFACE='$CTO_SURFACE'
DEV_SURFACE='$DEV_SURFACE'
QA_CLAUDE_SURFACE='$QA_CLAUDE_SURFACE'
QA_GEMINI_SURFACE='$QA_GEMINI_SURFACE'
RECON_SURFACE='$RECON_SURFACE'
EOF

# ─── Boot agents ───────────────────────────────────────────────────────────
echo "→ starting agents…"

send_cmd "$DEV_SURFACE" \
  "export ORCHESTRA_ROOT='$ORCHESTRA_ROOT'; clear; bash '$ORCHESTRA_ROOT/roles/dev.sh'"

send_cmd "$QA_CLAUDE_SURFACE" \
  "export ORCHESTRA_ROOT='$ORCHESTRA_ROOT'; clear; bash '$ORCHESTRA_ROOT/roles/qa-claude.sh'"

send_cmd "$QA_GEMINI_SURFACE" \
  "export ORCHESTRA_ROOT='$ORCHESTRA_ROOT'; clear; bash '$ORCHESTRA_ROOT/roles/qa-gemini.sh'"

send_cmd "$RECON_SURFACE" \
  "export ORCHESTRA_ROOT='$ORCHESTRA_ROOT'; clear; bash '$ORCHESTRA_ROOT/lib/reconciler.sh'"

# Re-focus CTO pane.
cmux focus-panel --panel "$CTO_SURFACE" --workspace "$WORKSPACE" >/dev/null

cat <<EOF

✓ team-orchestra is running.

  CTO       = $CTO_SURFACE  (this pane — talk to me here)
  DEV       = $DEV_SURFACE
  QA-CLAUDE = $QA_CLAUDE_SURFACE
  QA-GEMINI = $QA_GEMINI_SURFACE
  RECON     = $RECON_SURFACE

Helpers:
  ./bin/dispatch <task_id> <spec_file>     — send a spec to DEV
  ./bin/await-report <task_id>             — block until reconciled report
  ./bin/status                              — queue depths
  ./teardown-cmux.sh                        — close the agent panes

Refs are saved to .runtime/cmux.env.
EOF
