#!/usr/bin/env bash
# BE/FE-split 5-panel interactive multi-agent setup.
#
# Layout (CTO pane = this pane):
#   ┌──────┬──────┬──────┐
#   │ CTO  │ BE   │ FE   │
#   ├──────┼──────┴──────┤
#   │ QA-C │ QA-G        │
#   └──────┴─────────────┘
#
# - BE-Dev (Claude Sonnet 4.6) implements Spring Boot + FastAPI (src/, ai_server/)
# - FE-Dev (Claude Sonnet 4.6) implements Next.js 14 + Tailwind (client/)
# - QA-Claude / QA-Gemini verify independently
#
# CTO sends commands via `./.cmux/bin/say <be|fe|qa-claude|qa-gemini> "..."`.

set -euo pipefail
ORCHESTRA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export ORCHESTRA_ROOT

command -v cmux   >/dev/null || { echo "cmux CLI not found"   >&2; exit 1; }
command -v claude >/dev/null || { echo "claude CLI not found" >&2; exit 1; }
command -v gemini >/dev/null || { echo "gemini CLI not found" >&2; exit 1; }

WORKSPACE="${CMUX_WORKSPACE_ID:-$(cmux current-workspace | tr -d ' ')}"
echo "✓ workspace: $WORKSPACE"

list_surfaces() {
  cmux list-panels --workspace "$WORKSPACE" 2>/dev/null | grep -oE 'surface:[0-9]+' | sort -u
}

focused_surface() {
  cmux list-panels --workspace "$WORKSPACE" 2>/dev/null \
    | awk '/\[focused\]/ {for (i=1;i<=NF;i++) if ($i ~ /^surface:[0-9]+$/) {print $i; exit}}'
}

split_from() {
  local from="$1" dir="$2"
  cmux focus-panel --panel "$from" --workspace "$WORKSPACE" >/dev/null
  local before; before="$(list_surfaces)"
  cmux new-pane --direction "$dir" --workspace "$WORKSPACE" --focus false >/dev/null
  local tries=0 after new
  while (( tries < 30 )); do
    after="$(list_surfaces)"
    new="$(comm -13 <(echo "$before") <(echo "$after"))"
    if [[ -n "$new" ]]; then
      echo "$(echo "$new" | head -n1)"
      return 0
    fi
    sleep 0.1
    ((tries++))
  done
  echo "✗ split failed: $from $dir" >&2
  return 1
}

send_cmd() {
  local surface="$1" cmd="$2"
  cmux send-panel --panel "$surface" --workspace "$WORKSPACE" -- "$cmd"$'\n'
}

CTO_SURFACE="$(focused_surface)"
[[ -z "$CTO_SURFACE" ]] && { echo "✗ no focused pane" >&2; exit 1; }
echo "✓ CTO     = $CTO_SURFACE"

echo "→ creating BE-Dev (right of CTO)…"
BE_DEV_SURFACE="$(split_from "$CTO_SURFACE" right)"
echo "  BE-Dev    = $BE_DEV_SURFACE"

echo "→ creating FE-Dev (right of BE)…"
FE_DEV_SURFACE="$(split_from "$BE_DEV_SURFACE" right)"
echo "  FE-Dev    = $FE_DEV_SURFACE"

echo "→ creating QA-CLAUDE (below CTO)…"
QA_CLAUDE_SURFACE="$(split_from "$CTO_SURFACE" down)"
echo "  QA-CLAUDE = $QA_CLAUDE_SURFACE"

echo "→ creating QA-GEMINI (below BE-Dev)…"
QA_GEMINI_SURFACE="$(split_from "$BE_DEV_SURFACE" down)"
echo "  QA-GEMINI = $QA_GEMINI_SURFACE"

mkdir -p "$ORCHESTRA_ROOT/.runtime"
cat > "$ORCHESTRA_ROOT/.runtime/cmux.env" <<EOF
# Generated by setup-team-be-fe.sh on $(date '+%Y-%m-%d %H:%M:%S')
CMUX_WORKSPACE='$WORKSPACE'
CTO_SURFACE='$CTO_SURFACE'
BE_DEV_SURFACE='$BE_DEV_SURFACE'
FE_DEV_SURFACE='$FE_DEV_SURFACE'
QA_CLAUDE_SURFACE='$QA_CLAUDE_SURFACE'
QA_GEMINI_SURFACE='$QA_GEMINI_SURFACE'
DEV_SURFACE='$BE_DEV_SURFACE'
RECON_SURFACE=''
EOF

send_cmd "$BE_DEV_SURFACE" \
  "cd /Users/user/Downloads/pillmate; clear; claude --dangerously-skip-permissions --append-system-prompt-file '$ORCHESTRA_ROOT/prompts/be-dev.md'"

send_cmd "$FE_DEV_SURFACE" \
  "cd /Users/user/Downloads/pillmate; clear; claude --dangerously-skip-permissions --append-system-prompt-file '$ORCHESTRA_ROOT/prompts/fe-dev.md'"

send_cmd "$QA_CLAUDE_SURFACE" \
  "cd /Users/user/Downloads/pillmate; clear; claude --dangerously-skip-permissions --append-system-prompt-file '$ORCHESTRA_ROOT/prompts/qa-claude.md'"

send_cmd "$QA_GEMINI_SURFACE" \
  "cd /Users/user/Downloads/pillmate; clear; gemini --yolo"

cmux focus-panel --panel "$CTO_SURFACE" --workspace "$WORKSPACE" >/dev/null

cat <<EOF

✓ BE/FE-split team is up.

  CTO       = $CTO_SURFACE  (this pane — you control)
  BE-Dev    = $BE_DEV_SURFACE
  FE-Dev    = $FE_DEV_SURFACE
  QA-CLAUDE = $QA_CLAUDE_SURFACE
  QA-GEMINI = $QA_GEMINI_SURFACE

CTO 에서 메시지 보내기:
  ./.cmux/bin/say <be|fe|qa-claude|qa-gemini> "메시지"

Refs in .runtime/cmux.env.
EOF
