package com.pillmate.doselog.infrastructure.scheduler;

import com.pillmate.common.monitoring.SlackNotifier;
import com.pillmate.doselog.application.GenerateDailyDoseLogsUseCase;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Clock;
import java.time.LocalDate;
import java.time.ZoneId;

@Slf4j
@Component
public class DailyDoseLogScheduler {

    private static final ZoneId KST = ZoneId.of("Asia/Seoul");

    private final GenerateDailyDoseLogsUseCase generateDailyDoseLogs;
    private final Clock clock;
    private final Counter successCounter;
    private final Counter failureCounter;
    private final Counter generatedCounter;
    private final SlackNotifier slackNotifier;

    public DailyDoseLogScheduler(GenerateDailyDoseLogsUseCase generateDailyDoseLogs,
                                  Clock clock,
                                  MeterRegistry registry,
                                  SlackNotifier slackNotifier) {
        this.generateDailyDoseLogs = generateDailyDoseLogs;
        this.clock = clock;
        this.slackNotifier = slackNotifier;
        this.successCounter = Counter.builder("pillmate.doselog.scheduler.runs")
                .tag("result", "success")
                .description("Daily dose log scheduler successful runs")
                .register(registry);
        this.failureCounter = Counter.builder("pillmate.doselog.scheduler.runs")
                .tag("result", "failure")
                .description("Daily dose log scheduler failed runs")
                .register(registry);
        this.generatedCounter = Counter.builder("pillmate.doselog.scheduler.generated")
                .description("Total dose log slots generated by daily scheduler")
                .register(registry);
    }

    @Scheduled(cron = "0 0 0 * * *", zone = "Asia/Seoul")
    public void generateAtMidnight() {
        LocalDate today = LocalDate.now(clock.withZone(KST));
        log.info("DailyDoseLogScheduler midnight trigger date={}", today);
        runSafely(today);
    }

    @EventListener(ApplicationReadyEvent.class)
    public void generateOnStartup() {
        LocalDate today = LocalDate.now(clock.withZone(KST));
        log.info("DailyDoseLogScheduler startup trigger date={}", today);
        runSafely(today);
    }

    private void runSafely(LocalDate date) {
        try {
            int created = generateDailyDoseLogs.generate(date);
            successCounter.increment();
            generatedCounter.increment(created);
            if (created == 0) {
                log.warn("DailyDoseLogScheduler zero slots generated date={}", date);
                slackNotifier.send(String.format("⚠️ dose_log 생성 0건 (날짜 %s) — 처방 스케줄 확인 필요", date));
            } else {
                log.info("DailyDoseLogScheduler done date={} created={}", date, created);
            }
        } catch (RuntimeException ex) {
            failureCounter.increment();
            log.error("DailyDoseLogScheduler failed date={} reason={}", date, ex.getMessage(), ex);
            slackNotifier.send(String.format("🚨 dose_log 스케줄러 실패 (날짜 %s) reason=%s",
                    date, ex.getClass().getSimpleName()));
        }
    }
}
